---
title: "Modern Applied Data Analysis (MADA)"
sidebar:
  collapse-level: 1 
---

Welcome to the **Modern Applied Data Analysis (MADA)** course website.

This website contains almost all the content of an online graduate level course taught by [Andreas Handel](https://www.andreashandel.com/) at the University of Georgia. Most materials are hosted here, some are on external sites and either linked or embedded from here.

***The course is currently not running. The website will likely receive none or only minor updates until the next time the course will be offered (tentatively spring 2024).***

# Website content

The **General Information** section provides a class **Syllabus** and a **Schedule**. The latter will likely be updated throughout the course, so check it regularly. The **Communication** page provides information on how course communications are planned to happen. The **Assessments** explains how the different assignments and assessments for the course work.

The majority of the content is listed under the **Modules** heading. Each module has several units in a drop-down/pop-out menu. Go through them based on the instructions in the **Schedule.** Each module ends with a document listing the assessments that go with the module.

The **Project** section provides instructions and detailed information for the semester-long data analysis project which is part of the course.

The **Resources** section contains a **Course Resources** section with listings of materials that are most relevant to the course. Some of this material will assigned as part of this course. You will be told what exactly to read or work through in the modules documents. The **General Resources** section lists other resources in case you might find them helpful. All materials are (should be) available freely online. The **Glossary** section provides brief definitions of terms used in this course.

Note that by default, all links open in the current tab. You\'ll likely want external ones to open in a separate tab or window. To do so, you can (with most browsers) hold the `Ctrl` button when clicking, or do a right-click and select `open in new tab/window`.

# Getting started

Start by looking over the documents in the **General Information** section, then the **Resources** section. After that, start with the first **Module** content in the given order. You can read through the **Project** section early or wait until you have gone through the first few modules.

## Acknowledgements

This course was developed and is maintained by [Andreas Handel](https://www.andreashandel.com/).

The following individuals have contributed to improving the course: Ian Bachli ([\@idbachli](https://github.com/idbachli)), Megan Beaudry ([\@MeganSarah](https://github.com/MeganSarah)), Zane Billings ([\@wzbillings](https://github.com/wzbillings)), Amanda Blubaugh ([\@alblubaugh](https://github.com/alblubaugh)), Mia Carmichael ([\@mncarmic](https://github.com/mncarmic)), Ellen Cheng ([\@ellenmonster](https://github.com/ellenmonster)), Paige Duffin ([\@paigeduffin](https://github.com/paigeduffin)), Robert Edenfield ([\@ClaytonEdenfield](https://github.com/ClaytonEdenfield)), Julia Frederick ([\@JuliaFrederick](https://github.com/JuliaFrederick)), Savannah Hammerton ([\@smhammerton](https://github.com/smhammerton)), Megan Lott ([\@meganejlott](https://github.com/meganejlott)), Yao Lu ([\@yl3362](https://github.com/yl3362)), Brian McKay ([\@bmckay](https://github.com/bmckay)), William Norfolk ([\@williamnorfolk](https://github.com/williamnorfolk)), Trang Quach ([\@TrangQuach](https://github.com/TrangQuach)), Emily Rayens ([\@Rayense](https://github.com/Rayense)), Megan Robertson ([\@meganjro](https://github.com/meganjro)), Amanda Skarlupka ([\@askarlupka](https://github.com/askarlupka)), Jonathan Wilson ([\@JJWilson1991](https://github.com/JJWilson1991)), Yang Zhang ([\@yz17970](https://github.com/yz17970))

The course materials are licensed under the [Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License](http://creativecommons.org/licenses/by-nc-sa/4.0/). Linked and embedded materials are governed by their own licenses. I assume that all external materials used or embedded here are covered under the educational fair use policy. If this is not the case and any material displayed here violates copyright, please let me know and I will remove it.
